### ISSUE TITLE
Zero out per axis doesn't work

### ISSUE THREAD

**Issue by peteruithoven** [chilipeppr/tinyg#8] opened 2014-10-07 18:01 UTC
Using the GRBL workbench, in the *Axes panel*, the *Zero out* per axes zero's all axes. 
So under the X, Y, Z buttons, *Zero out X Axis (G28.3 X0)* for example. 
I can see it sends a `G92X0Y0Z0` in the *Serial Port Console*. 
So it also sends the wrong command type. 

(The *Zero out X Axis (G92 X0)* button does send the right command.)

**Comment by matthijskooijman** [comment] 2015-01-06 11:46
Confirmed, it works for me on our Mantis mill. Perhaps @peteruithoven can confirm on the big mill tonight :-)

**Comment by matthijskooijman** [comment] 2015-07-21 17:03
This issue is fixed, can someone close it?

**Closed** 2015-07-21 17:51 UTC
